### ISSUE TITLE
Develop strategy for indexing declarations made in C / native extensions

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#1335]
We currently index all Ruby files bundled with the Ruby installation, but that doesn't cover all declarations available. Core classes like `Array` or `String` are defined in C and thus we miss those declarations. We also miss gem declarations that are made in native extensions.

We need to consider the performance, accuracy and maintenance costs of a few different approaches to decide how we're going to handle this:

- RDoc uses regexes to extract declarations from C files directly. The problem with that is that the C files aren't always included in Ruby installations, so those files may not be there
- We could read the RDoc index objects, but that is also dependent on the installation since Ruby may be installed without documentation
- We can read and process RBS files. However, we'll miss gems that don't include RBS signatures
- We could also bundle empty declarations for the Core library in Ruby files, which is essentially what RBS signatures are. This would involve some manual work to create these files and we would need to ensure they are up to date based on Ruby versions
- Some other idea?

---

```[tasklist]
### Tasks
- [x] [Index Core classes using RBS](https://github.com/Shopify/ruby-lsp/pull/2132)
- [x] [Extract includes, prepends and extends and insert those as well](https://github.com/Shopify/ruby-lsp/pull/2148)
- [x] Index Core methods using RBS https://github.com/Shopify/ruby-lsp/pull/2157
- [ ] https://github.com/Shopify/ruby-lsp/issues/2328
- [ ] https://github.com/Shopify/ruby-lsp/issues/2327
- [ ] https://github.com/Shopify/ruby-lsp/issues/2326
- [ ] https://github.com/Shopify/ruby-lsp/issues/2329
```

**Comment by andyw8** [comment]
As per the team discussion earlier today, we will move ahead with using RBS declarations for indexing core class (String, Integer, etc).

**Comment by vinistock** [comment]
[This branch](https://github.com/Shopify/ruby-lsp/tree/vs/index_rbs) includes a super simple script for how to retrieve declarations which I paired on with Soutaro during RubyKaigi.

My understanding of it is that we can basically just iterate over the declarations that the code returns and then build our index's entries and push them.
