### ISSUE TITLE
Migrate requests to new emitter listener strategy

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#610]
After #607 goes in, we can start refactoring other requests to use the listener pattern. This will allow us to better understand what is missing for extensions to do their work, but it'll also allow us to execute all nonpositional requests in one round of visits, which should be great for performance.

Note: certain requests are simply not a good fit for the listener pattern (e.g.: formatting, on type formatting, code actions, code action resolve). We should keep those as they are for now.

```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/ruby-lsp/issues/655
- [ ] https://github.com/Shopify/ruby-lsp/issues/677
- [ ] https://github.com/Shopify/ruby-lsp/issues/646
- [ ] https://github.com/Shopify/ruby-lsp/issues/678
- [ ] https://github.com/Shopify/ruby-lsp/issues/659
- [ ] https://github.com/Shopify/ruby-lsp/issues/806
- [ ] https://github.com/Shopify/ruby-lsp/issues/661
- [ ] https://github.com/Shopify/ruby-lsp/issues/664
- [ ] https://github.com/Shopify/ruby-lsp/issues/702
```
