### ISSUE TITLE
2023-Q2 Roadmap

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#691]
# 2023-Q2 Roadmap

This public roadmap includes the planned iteration for the Ruby LSP during this quarter. If you're interested in contributing, see the [help wanted section](#help-wanted).

_Notice that we may add or change tasks that are listed._

## Theme

The theme for this quarter is Ruby LSP server extensions. We are working on building the mechanism that allows other gems to extend our functionality, so that we can have tool specific features easily added to the editor.

## Planned

```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/ruby-lsp/issues/690
- [ ] https://github.com/Shopify/ruby-lsp/issues/679
- [ ] https://github.com/Shopify/ruby-lsp/issues/678
- [ ] https://github.com/Shopify/ruby-lsp/issues/677
- [ ] https://github.com/Shopify/ruby-lsp/issues/664
- [ ] https://github.com/Shopify/ruby-lsp/issues/649
- [ ] https://github.com/Shopify/ruby-lsp/issues/611
- [ ] https://github.com/Shopify/ruby-lsp/issues/610
- [ ] https://github.com/Shopify/ruby-lsp/issues/590
- [ ] https://github.com/Shopify/ruby-lsp/issues/589
- [ ] https://github.com/Shopify/ruby-lsp/issues/588
- [ ] https://github.com/Shopify/vscode-ruby-lsp/issues/588
- [ ] https://github.com/Shopify/vscode-ruby-lsp/issues/550
- [ ] https://github.com/Shopify/ruby-lsp-rails/issues/52
- [ ] https://github.com/Shopify/ruby-lsp-rails/issues/44
- [ ] https://github.com/Shopify/ruby-lsp-rails/issues/29
- [ ] https://github.com/Shopify/ruby-lsp-rails/issues/7
```

## Help wanted

We tag issues that the community can help with using the [help-wanted](https://github.com/Shopify/ruby-lsp/issues?q=is%3Aissue+is%3Aopen+label%3Ahelp-wanted) label. These are tasks that our team will probably not have the capacity to tackle during this quarter, but we can assist members of the community to push it forward.

If you wish to contribute any of these tasks, but aren't sure where to start, do not hesitate in asking for guidance on the specific issue you'd like to tackle.

```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/ruby-lsp/issues/687
- [ ] https://github.com/Shopify/ruby-lsp/issues/684
- [ ] https://github.com/Shopify/ruby-lsp/issues/633
- [ ] https://github.com/Shopify/ruby-lsp/issues/585
- [ ] https://github.com/Shopify/ruby-lsp/issues/448
- [ ] https://github.com/Shopify/ruby-lsp/issues/272
- [ ] https://github.com/Shopify/ruby-lsp/issues/683
- [ ] https://github.com/Shopify/vscode-ruby-lsp/issues/585
```

## Next iteration

The next iteration will include further work in the server extensions system and code indexing, which unblocks go to definition, autocomplete, signature help, workspace symbols, etc.

**Comment by serioushaircut** [comment]
I stumbled upon this while checking that intellisense / rubyLocate not working/being supported.
It's not on this roadmap, is it? The comment in #589 suggested it is being worked on.

That'd be great :heart: . I miss this feature in every minute of using vs code. Strangely, it worked until recently - dunno whether I had other extensions enabled...
